### ISSUE TITLE
Request: Change the generated function for can_manage_billing?

### ISSUE THREAD

**Issue by hassanshaikley** [ozziexsh/bling#14]
I was wondering if `can_manage_billing?` should default to `conn.assigns.current_user.id === customer.id`.

Maybe it's good that it just returns false because it makes you familiarize yourself with the generated action. But I figured I would at least share my thoughts.

**Comment by ozziexsh** [comment]
hey I think that your PR #13 is a happy medium that now outlines you must fill this in. I'd rather have it too restrictive than too open
